spring.application.name=fisiovital-web-services
server.port=8080

# PostgreSQL (puedes sobrescribir con variables de entorno)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fisiovital}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# i18n (en_US y es_419)
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# JWT
app.jwt.secret=${JWT_SECRET:Rhuz3RyWcfctujSjVT9r77d/hyiiD252fSv4oMTm6BvuYrgK/8jwohKC3w0Zx6V6tvqTz6x33lWCOeuJN8T1ZQ==}
app.jwt.expiration-minutes=1440

# Recordatorios
app.reminders.hours-before=24
app.mail.from=${MAIL_FROM:no-reply@fisiovital.pe}

# Correo (opcional). Si no se configura, los recordatorios solo se guardan como notificacion en la plataforma.
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=${MAIL_USERNAME}
# spring.mail.password=${MAIL_PASSWORD}
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
